// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABt-yBeEdipdMvqe1OuKM2aOL25S0Via0',
    appId: '1:683722216857:web:42b7edd265fee92c3f6f08',
    messagingSenderId: '683722216857',
    projectId: 'fasum-marcel-ce5ef',
    authDomain: 'fasum-marcel-ce5ef.firebaseapp.com',
    storageBucket: 'fasum-marcel-ce5ef.appspot.com',
    measurementId: 'G-FY6HCE3P0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvEhQ0-g-6s5f_0L-9Qbomeg-GbVPBLmw',
    appId: '1:683722216857:android:485a786682c0f94f3f6f08',
    messagingSenderId: '683722216857',
    projectId: 'fasum-marcel-ce5ef',
    storageBucket: 'fasum-marcel-ce5ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvH5FTYuts6anLc-z14Tpp6W79vOcJm4A',
    appId: '1:683722216857:ios:9385767dbfa548823f6f08',
    messagingSenderId: '683722216857',
    projectId: 'fasum-marcel-ce5ef',
    storageBucket: 'fasum-marcel-ce5ef.appspot.com',
    iosClientId: '683722216857-o286591fusisfq5679r2vd156cpusaut.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasumMarcel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvH5FTYuts6anLc-z14Tpp6W79vOcJm4A',
    appId: '1:683722216857:ios:9385767dbfa548823f6f08',
    messagingSenderId: '683722216857',
    projectId: 'fasum-marcel-ce5ef',
    storageBucket: 'fasum-marcel-ce5ef.appspot.com',
    iosClientId: '683722216857-o286591fusisfq5679r2vd156cpusaut.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasumMarcel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABt-yBeEdipdMvqe1OuKM2aOL25S0Via0',
    appId: '1:683722216857:web:329d26b7fa7d5fde3f6f08',
    messagingSenderId: '683722216857',
    projectId: 'fasum-marcel-ce5ef',
    authDomain: 'fasum-marcel-ce5ef.firebaseapp.com',
    storageBucket: 'fasum-marcel-ce5ef.appspot.com',
    measurementId: 'G-QVPSNXFXNH',
  );

}